@host = http://localhost:5263

### Get all persons
GET {{host}}/person
Accept: application/json

### Get all addresses
GET {{host}}/addresses
Accept: application/json

### Get address types
GET {{host}}/addresstypes
Accept: application/json
